[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  identifier = "sitemap"
  name = "All Tools"
  url = "/sitemap/"
  weight = 15

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 20

[[main]]
  identifier = "authors"
  name = "Authors"
  url = "/tags/"
  weight = 30

[[main]]
  identifier = "tutorials"
  name = "Tutorials"
  url = "/categories/tutorials/"
  weight = 40

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 50
