contentTypeName = "posts"
themeColor = "dark"
showMenuItems = 5
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = false

[logo]
  logoText = "UO Tools Archive"
  logoHomeLink = "/"
