contentTypeName = "posts"
themeColor = "dark"
showMenuItems = 7
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = false
showLastUpdated = false
ReadMore = "Read More"

[logo]
  logoText = "UO Tools Archive"
  logoHomeLink = "/"
